##############################
# #     #     #      #     # #
#  #  #   HowT(w)o #   #  #  #
#   #      #     #       #   #
##############################
Settings:
  Language: de
  OS: win
# Aviable Languages:
# de - German
# en - English